// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cgmgtzxexpqajtjjuijt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNnbWd0enhleHBxYWp0amp1aWp0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU0ODM4MDUsImV4cCI6MjA1MTA1OTgwNX0.HnAP_cOQ6mhmmWNzjJqQlvaqK3jdc5XR5pMBeegKRUM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);